config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles do
    member do
      put "like", to: "articles#vote"
      put "dislike", to: "articles#downvote"
    end
  end

  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  is_impressionable
  acts_as_votable
  belongs_to :user


  validates :title, presence: true, uniqueness: true
  validates :body, presence: true

  # It returns the articles whose titles contain one or more words that form the query
  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("title like ?", "%#{query}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy, :upvote]

  before_filter :require_permission, only: [:edit, :destroy]

  def require_permission
    if current_user != Article.find(params[:id]).user
      redirect_to articles_url, alert: 'Thats not your kitty. Try it with your own kitty...'
    end
  end

  impressionist :actions=>[:show,:index]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    if params[:search]
      @articles = Article.search(params[:search]).order("created_at DESC")
    else
      @articles = Article.order("created_at DESC")
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
  end

  # GET /articles/new
  def new
    @article = current_user.articles.build
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def vote
    @article = Article.find(params[:id])
    @article.vote_by :voter => current_user, :duplicate => true
    redirect_to articles_url
  end

  def downvote
    @article = Article.find(params[:id])
    @article.vote_by :voter => current_user, :duplicate => true, :vote => 'bad'
    redirect_to articles_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :image, :id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article, html: { multiPart: true} do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="container">
  <h1>Editing Article</h1>

  <%= render 'form', article: @article %>

  <%= link_to 'Show', @article %> | <%= link_to 'Back', articles_path %>
</div>

app/views/articles/index.html.erb
<% unless user_signed_in? %>
  <script type="text/javascript">
    $('#myModal').modal('show');
  </script>
<% end %>
<div class="container">

  <br>

  <!-- STATS CHART -->
  <% unless params[:search] %>

  <div class="row">
    <div class="col-sm-12">
      <h3>Kitty Stats</h3>
      <div class="chart">

        <% viewsHash = Hash[ @articles.map{ |kitty| [kitty.title,kitty.impressionist_count] } ] %>
        <% votesHash = Hash[ @articles.map{ |kitty| [kitty.title,(kitty.get_upvotes.size - kitty.get_downvotes.size)] } ] %>

        <%= line_chart [
          {name: "Views", data: viewsHash},
          {name: "Rating", data: votesHash}
        ]%>

      </div>
    </div>
  </div>

  <br>
  <h3>Meet the Kitties &hellip;</h3>

  <% else %>

  <%= link_to 'Back to All', root_path, class: 'btn btn-primary' %>

  <br>
  <br>
  <h3>Search results for <%= params[:search] %> &hellip;</h3>

  <% end %>



  <div class="row">
    <div class="col-sm-12">

      <% @articles.each do |kitty| %>

      <div class="card">
        <div class="views text-white">
          <i class="icon-eye" style="display:inline-block;width: 30px;"></i> <span class="view-count" style="display:inline-block;min-width: 30px;"><%= kitty.impressionist_count %></span>
          <i class="icon-heart" style="display:inline-block;width: 30px;"></i> <span class="rating-count" style="display:inline-block;min-width: 30px;"><%= kitty.get_upvotes.size - kitty.get_downvotes.size%></span>
        </div>

        <div class="overlay">
          <div class="dislike text-white">
            <%= link_to dislike_article_path(kitty), method: :put, class: 'btn btn-outline-danger' do %>
              Hate
              <br>
              <i class="icon-thumbs-down"></i>
            <% end %>
          </div>
          <div class="like text-white">
            <%= link_to like_article_path(kitty), method: :put, class: 'btn btn-outline-success' do %>
              Dig
              <br>
              <i class="icon-thumbs-up"></i>
            <% end %>
          </div>
        </div>

        <img class="card-img-top img-fluid" src="<%= kitty.image.url(:large) %>" alt="Nature Rules">
        <div class="card-block">
          <h4 class="card-title"><%= kitty.title %><% kitty.object_id %></h4>
          <%= @markdown.render(kitty.body).html_safe %>
        </div>
        <div class="footer-toggle">
          <div class="card-footer">
            <%= link_to kitty, class: 'btn btn-primary' do %>
              <i class="icon-eye"></i> View
            <% end %>
            <%= link_to edit_article_path(kitty), class: 'btn btn-primary' do %>
              <i class="icon-pencil"></i> Edit
            <% end %>
            <%= link_to kitty, method: :delete, data: { confirm: 'Are you serious!?' }, class: 'btn btn-danger' do %>
              <i class="icon-sword"></i> Kill
            <% end %>
          </div>
        </div>
      </div>

      <% end %>

      <br>
      <% if params[:search] %>
        <%= link_to root_path, class: 'btn btn-primary' do %>
          <i class="icon-arrow-left"></i> Back to All Kitties
        <% end %>
      <% end %>

      <% if user_signed_in? %>
        <%= link_to new_article_path, class: 'btn btn-primary' do %>
          <i class="icon-plus"></i> New Kitty
        <% end %>
      <% end %>
      <br>
      <br>

    </div>
  </div>


</div>

app/views/articles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>New Kitty</h1>

      <%= render 'form', article: @article %>

      <%= link_to 'Back', articles_path %>

    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6">
        <%= image_tag @article.image.url(:large), :class => '.img-fluid' %>
      <p>
        <strong>Title:</strong>
        <%= @article.title %>
      </p>

      <p>
        <strong>About this kitty:</strong>
        <%= @markdown.render(@article.body).html_safe %>
      </p>
      <p>
        <strong>View Count:</strong>
        <%= @article.impressionist_count %>
      </p>

      <p>
        <strong>Submitted by:</strong>
        <%= @article.user.email %>
      </p>

      <%= link_to dislike_article_path(@article), method: :put, class: 'btn btn-outline-danger' do %>
        <i class="icon-thumbs-down"></i> Hate
      <% end %>
      <%= link_to like_article_path(@article), method: :put, class: 'btn btn-outline-success' do %>
        <i class="icon-thumbs-up"></i> Dig
      <% end %>

      <p style="padding-top: 15px;">- or -</p>

      <%= link_to articles_path, class: 'btn btn-secondary' do %>
        <i class="icon-arrow-left"></i> Back
      <% end %>
      <%= link_to edit_article_path(@article), class: 'btn btn-primary' do %>
        <i class="icon-pencil"></i> Edit
      <% end %>
      <%= link_to article_path, method: :delete, data: { confirm: 'Are you serious!?' }, class: 'btn btn-danger' do %>
        <i class="icon-sword"></i> Kill
      <% end %>
    </div>
    <div class="col-sm-3"></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RateMyKitty</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://i.icomoon.io/public/a8c6eb6311/TLock/style.css">
    <link href="https://fonts.googleapis.com/css?family=Varela+Round&amp;subset=vietnamese" rel="stylesheet">
  </head>

  <body>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <h4 class="modal-title" id="exampleModalLabel">Sign in to rate, edit, <strong>or even kill</strong> kitties!</h4>
          </div>
          <div class="modal-body">
            <p>You can create your own user, or demo this site as a guest by logging in as</p>
            <p>User: guest@ratemykitty.vn</p>
            <p>Password: supersecret</p>
          </div>
          <div class="modal-footer">
            <%= link_to 'Login', new_user_session_path, class: 'btn btn-success' %>

            <%= link_to 'Register', new_user_registration_path, class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    </div>

    <!-- Sign in/out and Search -->
    <div class="container" style="text-align: right;">

      <div class="search" style="float: left">
        <!-- When submit the form, the view rendered will be the index view of our articles resource -->
        <%= form_tag(articles_path, :method => "get", class: "navbar-form", id: "search-form") do %>
          <div class="input-append">
            <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Find A Specific Kitty" %>
            <!-- In order to have the "search" icon int the button, we need to use plain HTML instead
                 of using a Rails form helper -->
            <button class="btn btn-outline-primary" type="submit"><i class="icon-search"></i></button>
          </div>
        <% end %>
      </div>

      <% if user_signed_in? %>
        <small>
          You are signed in as <%= current_user.email %>.
          <%= link_to('Logout', destroy_user_session_path, :method => :delete ) %>
        </small>
      <% else %>
        <small>
          You are not logged in.
          <%= link_to 'Login', new_user_session_path %>
          or
          <%= link_to 'Register', new_user_registration_path %>
        </small>
      <% end %>
    </div>

    <!-- Main Header (alerts and branding) -->
    <div class="container">
      <div class="row">
        <div class="col-sm-12">

          <% if notice %>
          <div class="alert alert-info">
            <strong>Cool:</strong> <%= notice %>
          </div>
          <% end %>

          <% if alert %>
          <div class="alert alert-danger">
            <strong>Whoa, no way:</strong> <%= alert %>
          </div>
          <% end %>

          <h1><span>ratemykitty.vn</span><img src="<%= image_path('logo.png') %>" srcset="<%= image_path('logo@2x.png') %> 2x" style="display: inline-block"></h1>
        </div>
      </div>
    </div>

    <!-- Content -->
    <%= yield %>

  </body>
</html>